version: 1
module_version: 0.1.2

tests:
  - name: "Default pet test"
    project_root: examples/default
  - name: Same test
    project_root: examples/default
    negative: true
  - name: Same test #2
    project_root: examples/default
    negative: true
